eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,refresh,info,prometheus,gateway

  endpoint:
    gateway:
      enabled: true

    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0

  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:http://localhost:14318/v1/metrics}

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:14318/v1/traces}

    logging:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_LOGS_ENDPOINT:http://localhost:14318/v1/logs}

  logging:
    pattern:
      correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

outbox:
  poller:
    interval-ms: 5000