spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/authdb}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
outbox:
  poller:
    interval-ms: 5000

nats:
  url: ${NATS_URL:nats://localhost:4222}